### ISSUE TITLE
Failed in windows7

### ISSUE THREAD

**Issue by funtion** [n1k0/SublimeHighlight#48]
Win a try to copy as HTML,I could not paste anything.I got the error form the console:
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
    return self.run(edit, **args)
  File ".\SublimeHighlight.py", line 152, in run
  File ".\winclip__init__.py", line 57, in Paste
  File ".\winclip__init__.py", line 80, in Put
ValueError: Procedure probably called with too many arguments (8 bytes in excess)

**Comment by klashxx** [comment]
Thanks @Shoubi

**Comment by n1k0** [comment]
Could you guys create a PR for this?
