### ISSUE TITLE
Not Working on Ubuntu 16.04 64-bit with ST3

### ISSUE THREAD

**Issue by victorbrca** [n1k0/SublimeHighlight#68]
I tried installing it via package control, via the repo and via git clone, but none works. I get the menu settings and and the right click options, however right click options are disabled, and commands do not show up.  

It also seems that when using the repo (or git clone), if I try to go to default settings, it's looking under the Highlight folder, and not SublimeHighlight. 

Ubuntu 16.04.1 LTS 64-bit
Sublime Text Build 3114

**Comment by joelw** [comment]
I noticed something similar. Checking the console, the following error is visible:

```
reloading plugin SublimeHighlight.SublimeHighlight
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/user/.config/sublime-text-3/Packages/SublimeHighlight/SublimeHighlight.py", line 17, in <module>
    if desktop.get_desktop() == 'Windows':
  File "/home/user/.config/sublime-text-3/Packages/SublimeHighlight/HighlightLib/desktop/__init__.py", line 167, in get_desktop
    elif _is_xfce():
  File "/home/user/.config/sublime-text-3/Packages/SublimeHighlight/HighlightLib/desktop/__init__.py", line 138, in _is_xfce
    return _readfrom(_get_x11_vars() + "xprop -root _DT_SAVE_MODE", shell=1).strip().endswith(' = "xfce4"')
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

Google suggested changing line 138 to `endswith(b' = "xfce4"')` and doing so fixed the plugin for me. Not being a Python programmer, I have no idea if this is a valid fix so I'm not sure I want to submit a PR. Ah, someone has already submitted a fix (using a different method) in #57.
